source "https://rubygems.org"

gem "fastlane"
gem "dotenv"
gem 'aws-sdk-s3', '~> 1'
gem 'aws-sdk-cloudfront', '~> 1'

plugins_path = File.join(File.dirname(__FILE__), 'fastlane', 'Pluginfile')
eval_gemfile(plugins_path) if File.exist?(plugins_path)
